/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_1;

/**
 *
 * @author Nato
 */
public class InterfazBFSDFS extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazBFSDFS.class.getName());
    static Grafo_Vertices g;

    /**
     * Creates new form InterfazBusqueda
     */
    public InterfazBFSDFS(Grafo_Vertices g) {
        initComponents();
        this.g = g;
                this.setVisible(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dfs = new javax.swing.JTextField();
        bfs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hubs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan.setBackground(new java.awt.Color(102, 102, 102));
        pan.setForeground(new java.awt.Color(102, 102, 102));
        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ruta Metabolica mas Corta");
        pan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hubs");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 180, 40));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pan.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 160, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Recorrido:");
        pan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        dfs.setBackground(new java.awt.Color(153, 153, 153));
        dfs.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        dfs.setForeground(new java.awt.Color(255, 255, 255));
        dfs.addActionListener(this::dfsActionPerformed);
        pan.add(dfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 290, -1));

        bfs.setBackground(new java.awt.Color(153, 153, 153));
        bfs.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        bfs.setForeground(new java.awt.Color(255, 255, 255));
        bfs.addActionListener(this::bfsActionPerformed);
        pan.add(bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 290, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        pan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        boton.setBackground(new java.awt.Color(153, 153, 153));
        boton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 255, 255));
        boton.setText("BFS");
        boton.addActionListener(this::botonActionPerformed);
        pan.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, 40));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DFS");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        pan.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 180, 40));

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Recorrido:");
        pan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Recorrido:");
        pan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        hubs.setBackground(new java.awt.Color(153, 153, 153));
        hubs.setColumns(20);
        hubs.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        hubs.setForeground(new java.awt.Color(255, 255, 255));
        hubs.setRows(5);
        jScrollPane1.setViewportView(hubs);

        pan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 240, 320, 280));

        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1120, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Interfaz inter = new Interfaz(g);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your ha   
        hubs.setText(g.identificarHubs());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // TODO add your handling code here:
        bfs.setText(g.bfs());
    }//GEN-LAST:event_botonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: 
        dfs.setText(g.recorridoDFS());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_bfsActionPerformed

    private void dfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dfsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazBFSDFS(g).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bfs;
    private javax.swing.JButton boton;
    private javax.swing.JTextField dfs;
    private javax.swing.JTextArea hubs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pan;
    // End of variables declaration//GEN-END:variables
}
