/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_1;

import java.awt.BorderLayout;
import org.graphstream.algorithm.util.FibonacciHeap.Node;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author coco
 */
public class Interfaz extends javax.swing.JFrame {

    Grafo_Vertices g;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    private void dibujarGrafo() {
        if (this.g == null || this.g.getpFirst() == null) {
            return;
        }

        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("BioGraph_Proteinas");

        String stylesheet
                = "node {"
                + "   fill-color: #CCCCCC;"
                + "   size: 30px;"
                + "   text-size: 14px;"
                + "   text-alignment: at-right;"
                + "   text-color: black;"
                + "   stroke-mode: plain;"
                + "   stroke-color: #333333;"
                + "}"
                + "edge {"
                + "   fill-color: #666666;"
                + "   text-size: 12px;"
                + "}";
        graph.setAttribute("ui.stylesheet", stylesheet);

        Nodo_Vertice vAux = g.getpFirst();
        while (vAux != null) {

            graph.addNode(vAux.getpDato()).setAttribute("ui.label", vAux.getpDato());
            vAux = vAux.getpNext();
        }

        vAux = g.getpFirst();
        int edgeId = 0;
        while (vAux != null) {
            Nodo_Arista aAux = vAux.getLista_Aristas().getpFirst();
            while (aAux != null) {
                String idEdge = vAux.getpDato() + "-" + aAux.getpData().getpDato();
                String idEdgeInv = aAux.getpData().getpDato() + "-" + vAux.getpDato();

                if (graph.getEdge(idEdge) == null && graph.getEdge(idEdgeInv) == null) {
                    Edge e = graph.addEdge(String.valueOf(edgeId++),
                            vAux.getpDato(),
                            aAux.getpData().getpDato(),
                            false);
                    e.setAttribute("ui.label", aAux.getCosto_Interaccion());
                }
                aAux = aAux.getpNext();
            }
            vAux = vAux.getpNext();
        }

        aplicarColoresPorComplejo(graph);

        Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);

        pan.removeAll();
        pan.setLayout(new BorderLayout());
        pan.add(viewPanel, BorderLayout.CENTER);
        pan.revalidate();
        pan.repaint();
    }

    private void aplicarColoresPorComplejo(Graph graph) {
        String[] paletaColores = {"#FF5733", "#33FF57", "#3357FF", "#F333FF", "#FF33A1", "#33FFF5"};
        int colorIdx = 0;

        g.reinicio();
        Nodo_Vertice actual = g.getpFirst();

        while (actual != null) {
            if (!actual.visitado) {
                String color = paletaColores[colorIdx % paletaColores.length];

                marcarComplejoVisual(actual, color, graph);

                colorIdx++;
            }
            actual = actual.getpNext();
        }
        g.reinicio();
    }

    private void marcarComplejoVisual(Nodo_Vertice nodo, String color, Graph graph) {
        nodo.visitado = true;
        Node n = (Node) graph.getNode(nodo.getpDato());
        if (n != null) {
            graph.getNode(nodo.getpDato()).setAttribute("ui.style", "fill-color: " + color + ";");
        }

        Nodo_Arista arista = nodo.getLista_Aristas().getpFirst();
        while (arista != null) {
            if (!arista.getpData().visitado) {
                marcarComplejoVisual(arista.getpData(), color, graph);
            }
            arista = arista.getpNext();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan.setBackground(new java.awt.Color(102, 102, 102));
        pan.setForeground(new java.awt.Color(102, 102, 102));
        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU INICIAL");
        pan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Funciones Busqueda");
        pan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Funciones CSV");
        pan.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar Grafo");
        pan.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ver Grafo");
        pan.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pan;
    // End of variables declaration//GEN-END:variables
}
