/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_1;

import java.awt.BorderLayout;
import org.graphstream.algorithm.util.FibonacciHeap;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Nato
 */
public class InterfazGrafo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafo.class.getName());
    static Grafo_Vertices g;

    /**
     * Creates new form InterfazGrafo
     */
    public InterfazGrafo(Grafo_Vertices g) {
        initComponents();
        this.g = g;
        this.setVisible(true);
this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        try{
        this.imprimir();
        }catch(Exception e){
            
        }
    }

    private void imprimir() {
        if (g == null || g.getpFirst() == null) {
            return;
        }

        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("BioGraph_Proteinas");

        String stylesheet
                = "graph { fill-color: #222222; }"
                + "node { "
                + "   text-size: 16px; "
                + "   text-color: white; "
                + "   size: 25px; "
                + "   fill-color: #CCCCCC; "
                + "   text-alignment: at-right; "
                + "}"
                + "edge { "
                + "   fill-color: #666666; "
                + "   text-size: 12px; "
                + "   text-color: #AAAAAA; "
                + "}";
        graph.setAttribute("ui.stylesheet", stylesheet);

        Nodo_Vertice vAux = g.getpFirst();
        while (vAux != null) {
            if (graph.getNode(vAux.getpDato()) == null) {
                graph.addNode(vAux.getpDato()).setAttribute("ui.label", vAux.getpDato());
            }
            vAux = vAux.getpNext();
        }

        vAux = g.getpFirst();
        int edgeId = 0;
        while (vAux != null) {
            Nodo_Arista aAux = vAux.getLista_Aristas().getpFirst();
            while (aAux != null) {
                String origen = vAux.getpDato();
                String destino = aAux.getpData().getpDato();

                if (graph.getEdge(origen + "-" + destino) == null
                        && graph.getEdge(destino + "-" + origen) == null) {

                    try {
                        String idArista = origen + "-" + destino;
                        Edge e = graph.addEdge(idArista, origen, destino, false); 
                        e.setAttribute("ui.label", String.valueOf(aAux.getCosto_Interaccion()));
                    } catch (Exception ex) {
                    }
                }
                aAux = aAux.getpNext();
            }
            vAux = vAux.getpNext();
        }

        aplicarColoresPorComplejo(graph);
        
        Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);

        miPanel.removeAll();
        miPanel.setLayout(new java.awt.BorderLayout());
        miPanel.add(viewPanel, java.awt.BorderLayout.CENTER);
        miPanel.revalidate();
        miPanel.repaint();
    }

    private void aplicarColoresPorComplejo(Graph graph) {
        String[] paleta = {"red", "blue", "green", "gold", "purple", "orange", "cyan", "pink"};
        int colorIdx = 0;

        g.reinicio();
        Nodo_Vertice actual = g.getpFirst();

        while (actual != null) {
            if (!actual.visitado) {
                String color = paleta[colorIdx % paleta.length];
                marcarComponenteRecursivo(actual, color, graph);
                colorIdx++;
            }
            actual = actual.getpNext();
        }
    }

    private void marcarComponenteRecursivo(Nodo_Vertice nodo, String color, Graph graph) {
        nodo.visitado = true;
        org.graphstream.graph.Node n = graph.getNode(nodo.getpDato());
        if (n != null) {
            n.setAttribute("ui.style", "fill-color: " + color + ";");
        }

        Nodo_Arista arista = nodo.getLista_Aristas().getpFirst();
        while (arista != null) {
            if (!arista.getpData().visitado) {
                marcarComponenteRecursivo(arista.getpData(), color, graph);
            }
            arista = arista.getpNext();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(miPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazGrafo(g).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel miPanel;
    // End of variables declaration//GEN-END:variables
}
