/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_1;

import javax.swing.JOptionPane;

/**
 *
 * @author Nato
 */
public class ModifGrafo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModifGrafo.class.getName());
    static Grafo_Vertices g;

    /**
     * Creates new form ModifGrafo
     */
    public ModifGrafo(Grafo_Vertices g) {
        initComponents();
        this.g = g;
                this.setVisible(true);

        this.grafo.setText(g.imprimirGrafo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        peso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grafo = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        inicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        otro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan.setBackground(new java.awt.Color(102, 102, 102));
        pan.setForeground(new java.awt.Color(102, 102, 102));
        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peso");
        pan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Relacion");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        peso.setBackground(new java.awt.Color(153, 153, 153));
        peso.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        peso.setForeground(new java.awt.Color(255, 255, 255));
        pan.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 110, -1));

        grafo.setBackground(new java.awt.Color(153, 153, 153));
        grafo.setColumns(20);
        grafo.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        grafo.setForeground(new java.awt.Color(255, 255, 255));
        grafo.setRows(5);
        jScrollPane1.setViewportView(grafo);

        pan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, 360));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pan.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 20, 160, 40));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        pan.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar Grafo");
        pan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Proteinas actuales en el grafo");
        pan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de la Proteina");
        pan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        nombre.setBackground(new java.awt.Color(153, 153, 153));
        nombre.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        pan.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, -1));

        inicio.setBackground(new java.awt.Color(153, 153, 153));
        inicio.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.addActionListener(this::inicioActionPerformed);
        pan.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 270, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre de la Proteina");
        pan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        otro.setBackground(new java.awt.Color(153, 153, 153));
        otro.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        otro.setForeground(new java.awt.Color(255, 255, 255));
        pan.add(otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 290, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de la otra Proteina");
        pan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Interfaz inter = new Interfaz(g);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = this.nombre.getText();
        g.insertarVertice(name);
        this.nombre.setText("");
//        JOptionPane.showMessageDialog(rootPane, "Vertice añadido");
        this.grafo.setText(g.imprimirGrafo());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a = this.inicio.getText();
        String o = this.otro.getText();
        String p = this.peso.getText();
        try {
            g.insertarArista(a, o, Integer.parseInt(p));
            this.grafo.setText(g.imprimirGrafo());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Peso invalido");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ModifGrafo(g).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea grafo;
    private javax.swing.JTextField inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField otro;
    private javax.swing.JPanel pan;
    private javax.swing.JTextField peso;
    // End of variables declaration//GEN-END:variables
}
